"""Shared pagination classes."""

from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response


class StandardResultsSetPagination(PageNumberPagination):
    """Paginator that wraps results in a ``data`` and ``meta`` envelope."""

    page_size = 20
    page_size_query_param = "page_size"
    max_page_size = 100

    def get_paginated_response(self, data):
        """Build the paginated API response envelope.

        Args:
            data: Serialized page data.

        Returns:
            Response: Paginated response payload.
        """
        return Response(
            {
                "data": data,
                "meta": {
                    "count": self.page.paginator.count,
                    "next": self.get_next_link(),
                    "previous": self.get_previous_link(),
                },
            }
        )

    def get_paginated_response_schema(self, schema):
        """Build the OpenAPI schema for paginated responses.

        Args:
            schema: Item schema generated by DRF Spectacular.

        Returns:
            dict: OpenAPI-compatible schema for the envelope.
        """
        return {
            "type": "object",
            "properties": {
                "data": {"type": "array", "items": schema},
                "meta": {
                    "type": "object",
                    "properties": {
                        "count": {"type": "integer"},
                        "next": {"type": "string", "nullable": True},
                        "previous": {"type": "string", "nullable": True},
                    },
                },
            },
        }
