# Generated by Django 4.2.30 on 2026-05-08 04:10

import django.db.models.deletion
import uuid_extensions.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rentals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "type",
                    models.CharField(
                        choices=[("earned", "Earned"), ("redeemed", "Redeemed")], max_length=8
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_transactions",
                        to="rentals.rental",
                    ),
                ),
            ],
            options={
                "db_table": "reward_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
